apiVersion: v1
kind: Service
metadata:
  labels:
    name: veat-db
  name: veat-db
spec:
  clusterIP: 10.11.240.197
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: veat-db
  sessionAffinity: None
  type: ClusterIP
