# Generated by Django 2.0 on 2020-02-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elabels', '0002_auto_20200220_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_rate', to='elabels.Crop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RateUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('acronym', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='label',
            name='crop',
        ),
        migrations.AddField(
            model_name='applicationrate',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_rate', to='elabels.Label'),
        ),
        migrations.AddField(
            model_name='applicationrate',
            name='rate_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_rate', to='elabels.RateUnits'),
        ),
    ]
