# Generated by Django 2.0 on 2020-02-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elabels', '0003_auto_20200220_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient_Amount',
            new_name='IngredientAmount',
        ),
        migrations.RenameModel(
            old_name='RateUnits',
            new_name='RateUnit',
        ),
    ]
