# Generated by Django 2.0 on 2020-02-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elabels', '0004_auto_20200220_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrate',
            name='rate',
        ),
        migrations.AddField(
            model_name='applicationrate',
            name='max_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Maximum Rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationrate',
            name='min_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Minumum Rate'),
            preserve_default=False,
        ),
    ]
