# Generated by Django 2.0 on 2020-02-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elabels', '0005_auto_20200220_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrate',
            name='application_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application_rate', to='elabels.ApplicationMethod'),
            preserve_default=False,
        ),
    ]
